### ISSUE TITLE
Constant errors with 0.7.0

### ISSUE THREAD

**Issue by SpellChucker** [getsentry/sentry-cordova#32]
After upgrading to v0.7.0 I am constantly getting the following error in a loop:

```
Unhandled Promise rejection: this.isSetup is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.isSetup is not a function
```

**Comment by josephlimb** [comment]
This bug appears to be related: https://github.com/getsentry/raven-js/issues/1252

**Comment by HazAT** [comment]
I am working on a fix for this ref: https://github.com/getsentry/sentry-cordova/pull/34
